spring.application.name=grot-db

server.tomcat.threads.max=10

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/grot_db
spring.datasource.username=springuser
spring.datasource.password=ThePassword

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Uncomment the following two lines to dump SQL schema creation during startup. This is useful for updating schema.sql
# spring.jpa.hibernate.ddl-auto=create
# logging.level.org.hibernate.SQL=debug

# The following make Hibernate apply schema.sql and data.sql on startup
spring.sql.init.mode=always

# Dump SQL commands
# logging.level.org.hibernate.SQL=debug