discovery:
  # min_process_age: 15s
  instrument:
    - k8s_deployment_name: grot-db
    - k8s_deployment_name: frontend
attributes:
  kubernetes:
    enable: true
otel_metrics_export:
  features:
    - application
    - application_span
    - application_service_graph
    - application_process
    - network
    - application_host
    - network_inter_zone
  histogram_aggregation: base2_exponential_bucket_histogram
  interval: 10s
otel_traces_export:
ebpf:
  context_propagation: all