injector:
  webhook:
    enable: true
    port: 8443
    cert_path: /etc/webhook/certs/tls.crt
    key_path: /etc/webhook/certs/tls.key
  instrument:
    - k8s_namespace: default
  sdk_package_version: v0.0.4
  host_mount_path: /var/lib/beyla/instrumentation
discovery:
  # min_process_age: 15s
  instrument:
    - k8s_deployment_name: grot-db
    - k8s_deployment_name: frontend
attributes:
  kubernetes:
    enable: true
prometheus_export:
  port: 9999
  features:
    - application
    - application_span
    - application_service_graph
    - application_process
    - network
    - application_host
    - network_inter_zone
otel_traces_export:
  endpoint: http://tempo:4318
ebpf:
  context_propagation: all
