apiVersion: apps/v1
kind: Deployment
metadata:
  name: grot-db
  labels:
    app: grot-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grot-db
  template:
    metadata:
      labels:
        app: grot-db
    spec:
      initContainers:
      - name: otel-agent
        image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
        command: ["cp", "/javaagent.jar", "/otel/opentelemetry-javaagent.jar"]
        volumeMounts:
        - name: otel-agent
          mountPath: /otel
      containers:
      - name: grot-db
        image: fstab/2026-grafana-and-friends-munich_grot-db
        imagePullPolicy: Always
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/otel/opentelemetry-javaagent.jar"
        - name: OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION
          value: base2_exponential_bucket_histogram
        - name: OTEL_SERVICE_NAME
          value: grot-db
        - name: OTEL_EBPF_KUBE_CLUSTER_NAME
          value: "minikube"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=default,span.metrics.skip=true"
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(NODE_IP):4318
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: otel-agent
          mountPath: /otel
      volumes:
      - name: otel-agent
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grot-db
spec:
  selector:
    app: grot-db
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
